#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# polkit para abrir apps con sudo
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# lanzar dunst para las notificaciones popup
pkill -x dunst
dunst -conf $HOME/.config/dunst/dunstrc &

# lanzar polybar
sleep 1
$HOME/.config/polybar/launch.sh &

# lanzar conky
pkill -x conky
#conky --config $HOME/.config/conky/conky.conf &
conky --config $HOME/.config/conky/qclocktwo.conf &
conky --config $HOME/.config/conky/shortcuts.conf &
conky --config $HOME/.config/conky/macchiato.conf &

# lanzar picom
pkill -x picom
#pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
# lo quito porque hace algunos menues muy transparentes
# y la verdad que la transparencia no me llama tanto tanto.
# me ahorro unos megas. :)

# lanzar nm-tray para información de conexión de red
pgrep -x nm-tray > /dev/null || nm-tray &

#######################
# listado de desktops #
#######################
bspc monitor -d I II III IV V VI VII VIII IX X

#############################
# configuracion de ventanas #
#############################
bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# load colors
. "${HOME}/.config/bspwm/colors.sh"

bspc config normal_border_color    "$surface2"    # surface2. ventana no activa y sin foco
bspc config active_border_color    "$rosewater"   # rosewater. ventana activa pero sin foco (2 monitores)
bspc config focused_border_color   "$mauve_dark"  # mauve. ventana activo y con foco
bspc config presel_feedback_color  "$mauve_dark"  # mauve. preselección de ventana
bspc config urgent_border_color    "$red"         # red. ventana marcada como urgente

# verificar si cuando se tienen dos pantallas no genera conflicto al cerrar ambas ventanas
# de los dos monitores. Si es asi, deshabilitar o quitar esta opcion.
bspc config focus_follows_pointer  true  # hace focus segun donde este el mouse

###########################################
# reglas y comportamiento de aplicaciones #
###########################################
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox-esr desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a mpv state=fullscreen



# Manejo de reglas.
# source: https://github.com/awfixer-org/axyl-bspwm/blob/master/etc/skel/.config/bspwm/bspwmrc

# workspace 1 (Terminals)
#declare -a terminal=(Alacritty Xfce4-terminal)
#for i in ${terminal[@]}; do
#    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
#declare -a web=(firefox discord)
#for i in ${web[@]}; do
#    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
#declare -a filem=(Thunar Pcmanfm qBittorrent)
#for i in ${filem[@]}; do
#    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
#declare -a office=(Code Geany)
#for i in ${office[@]}; do
#    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
#declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
#"VirtualBox Manager")
#for i in ${media[@]}; do
#    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
#declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
#Pavucontrol Xfce4-settings-manager)
#for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
#declare -a floats=(Alafloat Lxappearance Arandr \
#Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
#for i in ${floats[@]}; do
#  bspc rule -a $i state=floating follow=on focus=on; done


