#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# polkit para abrir apps con sudo
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# lanzar dunst para las notificaciones popup
pkill dunst
dunst -conf $HOME/.config/dunst/dunstrc &

# lanzar polybar
sleep 1
$HOME/.config/polybar/launch.sh &

# lanzar conky
pkill conky
conky --config $HOME/.config/conky/conky.conf &
conky --config $HOME/.config/conky/qclocktwo.conf &
conky --config $HOME/.config/conky/shortcuts.conf &
conky --config $HOME/.config/conky/macchiato.conf &

# lanzar picom
pkill picom
#pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
# lo quito porque hace algunos menues muy transparentes
# y la verdad que la transparencia no me llama tanto tanto.
# me ahorro unos megas. :)

# lanzar nm-tray para información de conexión de red
pgrep -x nm-tray > /dev/null || nm-tray &

#######################
# listado de desktops #
#######################
bspc monitor -d I II III IV V VI VII VIII IX X

#############################
# configuracion de ventanas #
#############################
bspc config border_width         2
bspc config window_gap           12
bspc config normal_border_color  "#5B6078"  # surface2. ventana no activa y sin foco
bspc config active_border_color  "#EE99A0"  # maroon. ventana activa pero sin foco (2 monitores)
bspc config focused_border_color "#AD8EE6" # "#C6A0F6"  # mauve. ventana activo y con foco
bspc config presel_feedback_color "#F4DBD6"  # rosewater. preselección de ventana

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# verificar si cuando se tienen dos pantallas no genera conflicto al cerrar ambas ventanas
# de los dos monitores. Si es asi, deshabilitar o quitar esta opcion.
bspc config focus_follows_pointer  true  # hace focus segun donde este el mouse

###########################################
# reglas y comportamiento de aplicaciones #
###########################################
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^5' follow=on
