[ids]
*

[main]
capslock = overload(capslock, esc)

# Capslock will behave as control except for this specific cases.
[capslock:C]
tab = capslock
space = enter

backspace = delete
comma = C-backspace
dot = C-delete

u = pagedown
i = pageup
o = home
p = end

h = left
j = down
k = up
l = right

# Tapping both shift keys will activate capslock.
[shift]
leftshift = capslock
rightshift = capslock
